# Generated by Django 3.2.5 on 2021-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party', models.CharField(blank=True, max_length=50, null=True)),
                ('ACofParty', models.CharField(blank=True, max_length=50, null=True)),
                ('Movement', models.CharField(blank=True, max_length=10, null=True)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('PartyRef', models.CharField(blank=True, max_length=50, null=True)),
                ('ContainerNo', models.CharField(blank=True, max_length=11, null=True)),
                ('From', models.CharField(blank=True, max_length=30, null=True)),
                ('To1', models.CharField(blank=True, max_length=30, null=True)),
                ('To2', models.CharField(blank=True, max_length=30, null=True)),
                ('VehicleNo', models.CharField(blank=True, max_length=10, null=True)),
                ('TransporterName', models.CharField(blank=True, max_length=25, null=True)),
                ('InvoiceNo', models.IntegerField(blank=True, null=True)),
                ('InvoiceDate', models.CharField(blank=True, max_length=10, null=True)),
                ('InvoiceAmount', models.IntegerField(blank=True, null=True)),
                ('TripSheetNo', models.IntegerField(blank=True, null=True)),
                ('TripSheetAmount', models.IntegerField(blank=True, null=True)),
                ('TripSheetDate', models.CharField(blank=True, default='13-07-2021', max_length=10, null=True)),
                ('CashAdvance', models.IntegerField(blank=True, null=True)),
                ('ChequeAdvance', models.IntegerField(blank=True, null=True)),
                ('Fixed_Advance', models.IntegerField(blank=True, null=True)),
                ('Diesel', models.IntegerField(blank=True, null=True)),
                ('Alloted_Diesel', models.IntegerField(blank=True, null=True)),
                ('Diesel_Advance', models.IntegerField(blank=True, null=True)),
                ('Fixed_Diesel_Advance', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('Driver_Name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNo', models.CharField(default=None, max_length=10)),
                ('Amount', models.IntegerField()),
                ('Reason', models.CharField(default=None, max_length=100)),
                ('Reason_Id', models.IntegerField(default=0)),
                ('Date', models.CharField(default='13-07-2021', max_length=10)),
            ],
        ),
    ]
