# Generated by Django 3.2.5 on 2021-07-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_reg', '0002_auto_20210716_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='TripSheetDate',
            field=models.CharField(blank=True, default='20-07-2021', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='Date',
            field=models.CharField(default='20-07-2021', max_length=10),
        ),
    ]
