# Generated by Django 3.2.5 on 2021-07-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_reg', '0004_auto_20210729_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='TripSheetDate',
            field=models.CharField(blank=True, default='30-07-2021', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='Date',
            field=models.CharField(default='30-07-2021', max_length=10),
        ),
    ]
