# Generated by Django 3.2.5 on 2021-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_reg', '0006_auto_20210802_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='TripSheetDate',
            field=models.CharField(blank=True, default='04-08-2021', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='Date',
            field=models.CharField(default='04-08-2021', max_length=10),
        ),
    ]
