# Generated by Django 3.2.5 on 2021-08-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_reg', '0007_auto_20210804_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='movement',
            name='TripSheetDate',
            field=models.CharField(blank=True, default='05-08-2021', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='Date',
            field=models.CharField(default='05-08-2021', max_length=10),
        ),
    ]
