# Generated by Django 3.2.5 on 2021-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_reg', '0008_auto_20210805_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='TripSheetDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='Date',
            field=models.CharField(max_length=10),
        ),
    ]
